### ISSUE TITLE
First code example in doc/introduction.adoc does not compile

### ISSUE THREAD

**Issue by jcoder58** [YarikTH/ureact#129]
The following code from `doc/introduction.adoc` does not compile with the latest code.  make_var is undefined.
        
    #include "ureact/signal.hpp"
    #include "ureact/context.hpp"
    #include "ureact/observer.hpp"
    #include "ureact/events.hpp"
    #include "ureact/observer.hpp"
   
    using namespace ureact;
    using namespace ureact::default_context;

    void x() {
        var_signal<int> b = make_var(1);
        var_signal<int> c = make_var(2);
    }

Attempted with Microsoft Visual Studio Community 2022 (64-bit) - Version 17.7.3

**Comment by YarikTH** [comment]
```c++
#include <ureact/signal.hpp>
#include <ureact/adaptor/lift.hpp>

using namespace ureact;
using namespace ureact::default_context;
```

Are omitted. It is not clearly mentioned anywhere and I fixed some of similar cases in the dev branch. But `doc/introduction.adoc` is not fixed yet even in dev. Thanks for the mentioning.

**Comment by jcoder58** [comment]
I've updated my comment with the changed code (after your reply).  The namespace ureact is undefined using the includes shown in the first comment.

**Comment by YarikTH** [comment]
Could you provide the exact error messages? It is very strange if includes are found, but they are no provide the ureact namespace

**Comment by jcoder58** [comment]
Actually, it turns out to be a bug in Visual Studio.  Intellisense was showing the error, but it compiled with no errors.  I had to rebuild the intellisense database to have VS recognize the symbols.

**Comment by YarikTH** [comment]
If you use ureact in MSVC without CMake, only passing include directory, then you might be missing "/Zc:__cplusplus" flag.
Ureact used __cplusplus for standard detection, but MSVC reports the wrong version by default. See
https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/
