### ISSUE TITLE
Potential license issue

### ISSUE THREAD

**Issue by alexezeder** [YarikTH/ureact#36]
IANAL, but it looks like code from the [original project](https://github.com/snakster/cpp.react) which is [licensed under Boost license](https://github.com/snakster/cpp.react/blob/master/LICENSE_1_0.txt) cannot be relicensed under MIT license.
Here the link with similar question on StackExchange: https://opensource.stackexchange.com/a/2797.
Maybe the maintainer of the original project can give you permission to relicense the original code, if the problem with licenses is real.

**Comment by YarikTH** [comment]
I wrote to the author of the [original project](https://github.com/snakster/cpp.react). We'll see what he thinks. Changing the licence back to BSL and mentioned him as author up to 2020 is not a problem I think.

**Comment by YarikTH** [comment]
I'll change the licence to BSL, and add https://github.com/snakster as a maintainer till 2017. I hope it would completely solve the licence problem.
